### ISSUE TITLE
dist_path.txt is not vcs friendly and maybe unnecessary.

### ISSUE THREAD

**Issue by ReneGa** [winfinit/mongodb-prebuilt#22]
dist_path.txt references the absolute path to dist/ on installation. The issue is, when pulled from a vcs, it is most likely wrong and mongodb-prebuilt will not run.

This could be fixed by not reading from a textfile at all, but use __dirname + './dist/' instead, which should always give the correct path to dist/.

**Comment by winfinit** [comment]
@ReneGa thank you for reporting this issue, dist_path should actually not be in a version control at all, it is created during installation process, and gitignore excludes it. I need to look now why i didn't use __dirname, I think it is because you can specify your own dist path through options in mongodb-download, but Ill check it out to post more accurate update to this.

**Comment by ReneGa** [comment]
@winfinit thank you for the fast reply. While .gitignore lists the dist directory, dist_path.txt is in the root directory, and thus not affected by .gitignore. I think it should be added to the .gitignore as well.

**Comment by cyberwombat** [comment]
Any progress on this issue? Its seems to be a showstopper. 

```
 Uncaught Error: ENOENT: no such file or directory, open '...myapp/node_modules/mongodb-prebuilt/dist_path.txt'
```

**Comment by winfinit** [comment]
it is deprecated with 6.x release
